name: vinxes_store
description: A new Flutter project.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: '>=3.5.0 <4.0.0'


dependencies:
  flutter:
    sdk: flutter

  # Utility Packages
  http: ^1.1.0
  intl: ^0.19.0
  logger: ^2.0.1
  lottie: ^3.1.2
  connectivity_plus: ^6.0.5
  url_launcher: ^6.1.12
  flutter_native_splash: ^2.3.2
  smooth_page_indicator: ^1.1.0
  carousel_slider: ^5.0.0
  percent_indicator: ^4.0.1
  
  google_fonts: ^6.1.0
  # Icons
  iconsax: ^0.0.8
  cupertino_icons: ^1.0.2

  # State management
  get: ^4.6.6
  get_storage: ^2.1.1

  # Product specifics
  readmore: ^3.0.0
  flutter_rating_bar: ^4.0.1

  # FireBase
  firebase_core: ^2.23.0
  firebase_auth: ^4.16.0
  cloud_firestore: ^4.17.5

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^4.0.0
  win32: ^5.5.4


# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/on_boarding_images/
    - assets/images/animated_images/
    - assets/images/category_icons/
    - assets/images/carousel_images/
    - assets/images/products/
    - assets/images/user/
    - assets/icons/payment_methods/
    - assets/logos/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

flutter_native_splash:
  color: "#272727"
  image: assets/logos/my-logo.png
  android: true
  ios: true

  android_12:
    color: "#FFFFFF"
    color_dark: "#272727"
    image: assets/logos/my-logo.png
    android: true

 